<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2020 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace ShugaChara\Framework\Console\Commands;

use ShugaChara\Console\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class ApplicationCommand
 * @package ShugaChara\Framework\Console
 */
class ApplicationCommand extends Command
{
    protected static $name = 'application';

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this
            ->setName(static::$name)
            ->setDescription('获取 Applincation 应用信息');
    }

    /**
     * @param InputInterface  $input
     * @param OutputInterface $output
     * @return int
     */
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        // TYPE = [CLASS, CONTAINER, FRAMEWORK, PHP]
        $this->table(
            ['TYPE', 'NAME', 'CONTENT_NAME', 'CONTENT'],
            [
                [
                    'PHP', '', 'php 版本', phpversion()
                ],
                [
                    'PHP', '', 'swoole 版本', SWOOLE_VERSION
                ],
                [
                    'FRAMEWORK', '', '内核框架名称', get_framework_name()
                ],
                [
                    'FRAMEWORK', '', '内核框架版本', get_framework_version()
                ],
                [
                    'CLASS', 'Application', '应用名称', app()->getAppName()
                ],
                [
                    'CLASS', 'Application', '应用版本', app()->getAppVersion()
                ],
                [
                    'CLASS', 'Application', '应用根路径', app()->getAppBasePath()
                ],
                [
                    'CONTAINER', '', '容器服务名', implode(',', container()->getContainerServiceNames())
                ],
            ],
            'default'
        );

        return 0;
    }
}

