<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2019 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace ShugaChara\Framework\Console\Commands;

use ShugaChara\Console\Command;
use ShugaChara\Framework\Constant\Consts;
use ShugaChara\Framework\Server\SwooleServer;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

/**
 * Class SwooleCommand
 * @package ShugaChara\Framework\Console\Commands
 */
class SwooleCommand extends Command
{
    protected static $name = 'swoole';

    /**
     * 操作状态类型
     * @var array
     */
    protected $handleType = [
        Consts::SWOOLE_SERVER_START_NAME,
        Consts::SWOOLE_SERVER_STATUS_NAME,
        Consts::SWOOLE_SERVER_STOP_NAME,
        Consts::SWOOLE_SERVER_RELOAD_NAME,
        Consts::SWOOLE_SERVER_RESTART_NAME,
    ];

    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this
            ->setName(self::$name)  // 命令的名称
            ->setDescription('创建一个swoole服务器')  // 简短描述
            ->setHelp('创建一个http服务器:支持 http/websocket')  // 运行命令时使用 "--help" 选项时的完整命令描述
            ->addArgument('server_name', InputArgument::OPTIONAL, '服务名称 [http|websocket]')  // 配置可选参数
            ->addArgument('handle', InputArgument::OPTIONAL, '服务状态 [status|start|stop|reload|restart]')
            ->addArgument('daemonize', InputArgument::OPTIONAL, '守护进程 [d|daemon|daemonize]');
    }

    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $server_name = strtoupper($input->getArgument('server_name')) ?? Consts::SWOOLE_SERVER_HTTP;
        $handle = $input->getArgument('handle') ?? Consts::SWOOLE_SERVER_STATUS_NAME;
        $daemonize = in_array($input->getArgument('daemonize'), ['d', 'daemon', 'daemonize']) ? true : false;

        if (in_array($server_name, [
            Consts::SWOOLE_SERVER_HTTP,
            Consts::SWOOLE_SERVER_WEBSOCKET
        ])) {
            $config = config()->get('APP_SWOOLE.' . $server_name);

            // 配置守护进程
            if ($daemonize) {
                $config['options']['daemonize'] = $daemonize;
            }

            $SwooleServer = new SwooleServer($server_name, $config, $output);
            if (in_array($handle, $this->handleType)) {
                $SwooleServer->$handle();
            }
        }
    }
}

