<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2020 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace ShugaChara\Framework\Contracts;

use Exception;
use ShugaChara\Core\Utils\Helper\PhpHelper;
use ShugaChara\Framework\Traits\Swoole;
use ShugaChara\Framework\Traits\SwooleCommand;
use Throwable;
use ReflectionClass;
use swoole_process;
use swoole_server;
use ShugaChara\Framework\Console\Command;
use ShugaChara\Swoole\SwooleHelper;
use Symfony\Component\Console\Input\InputArgument;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Input\InputOption;

/**
 * Class BaseServerCommandAbstract
 * @package ShugaChara\Framework\Contracts
 */
abstract class BaseServerCommandAbstract extends Command implements StatusManagerInterface
{
    use Swoole, SwooleCommand;

    /**
     * Console configure
     */
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this->addArgument('status', InputArgument::OPTIONAL, 'Service status');
        $this->addOption('daemon', 'd', InputOption::VALUE_NONE, 'Service daemon');
    }

    /**
     * 初始化服务
     * @param                $server_name
     * @param InputInterface $input
     * @return int
     * @throws Exception
     */
    protected function initServer($server_name, InputInterface $input)
    {
        // 注册服务器命令行通道
        container()->add('server_channel', $this);

        // 设置服务名称
        $this->setServerName($server_name);

        $status = strtolower($input->getArgument('status')) ? : static::STATUS_NAME;
        $daemon = $input->hasParameterOption(['--daemon', '-d'], true) ? true : false;
        if (! in_array($status, self::STATUS_TYPES)) {
            throw new Exception($status . ' 服务状态未定义，请通过 --help 检查命令');
        }

        // 设置服务守护进程
        if ($daemon) {
            $this->setDaemonize($daemon);
        }

        $this->$status();
    }

    /**
     * 获取服务状态
     * @return mixed|void
     * @throws Exception
     */
    public function status()
    {
        // TODO: Implement status() method.

        if (! $this->getServerStatus()) {
            throw new Exception($this->getServerConfigName() . ' 服务未启动');
        }

        // 获取服务状态详情
        $this->getSwooleServerStatusInfo();

        return $this->writelnBlock($this->getServerConfigName() . ' 服务已启动');
    }

    /**
     * 服务启动
     * @return mixed|void
     * @throws Exception
     */
    public function start()
    {
        // TODO: Implement start() method.

        // 创建服务
        $this->getSwooleServer()->createServer(
            $this->getServerName(),
            $this->getServerConfig('port'),
            $this->getServerConfig('host', '0.0.0.0'),
            $this->getServerConfig('setting', [])
        );

        // 注册默认的回调事件
        $this->getSwooleServer()->registerDefaultCallback(
            $this->getSwooleServer()->getServer(),
            $this->getServerName()
        );

        // 注册当前类回调事件
        $selfEvents = get_class_methods($this);
        foreach ($selfEvents as $event) {
            if ('on' != substr($event, 0, 2)) {
                continue;
            }

            $this->getSwooleServer()->getEventsRegister()->addEvent(lcfirst(substr($event, 2)), [$this, $event]);
        }

        // 加载进程
        $this->getSwooleServer()->loadProcessor();

        // 加载监听
        $this->getSwooleServer()->loadListener();

        // 注册全局 Hook mainSwooleServerEventsCreate 事件
        $this->handleMainSwooleServerEventsCreate();

        // 进程 PID 文件
        $this->createSwooleSettingPidDir();

        // 设置主进程名称
        SwooleHelper::setProcessRename($this->getMasterProcessName());

        // 打印服务信息
        $this->serverInfo();

        // 服务启动
        $this->getSwooleServer()->start();
    }

    /**
     * 服务停止
     * @return mixed|void
     * @throws Exception
     */
    public function stop()
    {
        // TODO: Implement stop() method.

        $pidFile = $this->getSwooleSettingPidFile();
        if (file_exists($pidFile)) {
            $pid = intval(file_get_contents($pidFile));
            if (! swoole_process::kill($pid, 0)) {
                throw new Exception("服务 PID : {$pid} 不存在 ");
            }

            swoole_process::kill($pid);

            // Wait 5 seconds
            $time = time();
            while (true) {
                usleep(1000);
                if (! swoole_process::kill($pid, 0)) {
                    if (is_file($pidFile)) {
                        unlink($pidFile);
                    }
                    return $this->writelnBlock('服务停止时间 : ' . date('Y-m-d H:i:s'));
                    break;
                } else {
                    if (time() - $time > 15) {
                        throw new Exception('服务停止失败 , 异常：请尝试强制停止服务或kill进程');
                        break;
                    }
                }
            }

            throw new Exception('服务停止失败');
        }

        throw new Exception('服务PID文件不存在，请检查它是否在守护程序模式下运行！');
    }

    /**
     * 服务平滑加载
     * @return mixed|void
     * @throws Exception
     */
    public function reload()
    {
        // TODO: Implement reload() method.

        $pidFile = $this->getSwooleSettingPidFile();
        if (file_exists($pidFile)) {
            PhpHelper::opCacheClear();
            $pid = file_get_contents($pidFile);
            if (! swoole_process::kill($pid, 0)) {
                throw new Exception("服务 PID : {$pid} 不存在");
            }
            swoole_process::kill($pid, SIGUSR1);
            $this->writelnBlock('服务 PID: ' . $pid . ' 正在向所有工作进程发送平滑加载通知服务, 于 ' . date('Y-m-d H:i:s') . ' 完成加载');
            return ;
        }

        throw new Exception('服务PID文件不存在，请检查它是否在守护程序模式下运行！');
    }

    /**
     * 服务重启
     * @return mixed|void
     * @throws Exception
     */
    public function restart()
    {
        // TODO: Implement restart() method.

        $this->stop();

        $this->start();
    }

    /**
     * 获取服务运行状态
     * @return bool
     */
    protected function getServerStatus()
    {
        $pidFile = $this->getSwooleSettingPidFile();
        if (file_exists($pidFile)) {
            // 向进程发送信号，成功表示它处于运行状态
            return posix_kill(intval(file_get_contents($pidFile)), 0);
        }

        if ($is_running = SwooleHelper::processIsRunning($this->getMasterProcessName())) {
            $is_running = SwooleHelper::portIsRunning($this->getServerConfig('port'));
        }

        return $is_running;
    }

    /**
     * 获取Swoole服务状态信息
     */
    protected function getSwooleServerStatusInfo()
    {
        exec("ps axu | grep '{$this->getServerConfigName()}' | grep -v grep", $output);

        // 进程列表
        $rows = SwooleHelper::getAllProcess($this->getServerConfigName());

        $headers = ['USER', 'PID', 'RSS', 'STAT', 'START', 'COMMAND'];
        foreach ($rows as $key => $value) {
            $rows[$key] = array_combine($headers, $value);
        }

        $this->getIO()->table($headers, $rows);

        unset($table, $headers, $output);
    }

    /**
     * 处理全局 mainSwooleServerEventsCreate 事件
     */
    protected function handleMainSwooleServerEventsCreate()
    {
        $swooleMainEventsClass = fnc()->c()->get('swoole.main_events');
        if (class_exists($swooleMainEventsClass)) {
            try {
                $refSwooleMainEvents = new ReflectionClass($swooleMainEventsClass);
                if(! $refSwooleMainEvents->implementsInterface(MainSwooleEventsInterface::class)){
                    throw new Exception('MainSwooleEventsInterface 的全局文件不兼容 ' . $swooleMainEventsClass);
                }
                unset($refSwooleMainEvents);
            } catch (Throwable $throwable){
                throw new Exception($throwable->getMessage());
            }
        } else {
            throw new Exception('缺少全局事件文件');
        }

        $class = new $swooleMainEventsClass();

        // 初始化处理
        $class->initialize();

        // 注册 Swoole 事件
        $classFunctions = get_class_methods($class);
        foreach ($classFunctions as $event) {
            if ('on' != substr($event, 0, 2)) {
                continue;
            }

            $this->getSwooleServer()->getEventsRegister()->addEvent(lcfirst(substr($event, 2)), [$class, $event]);
        }

        // Swoole 处理
        $class->mainSwooleServerEventsCreate(
            $this->getSwooleServer()->getEventsRegister(),
            $this->getSwooleServer()->getServer()
        );
    }

    /**
     * 启动后在主进程（master）的主线程中调用此函数
     * @param swoole_server $server
     * @throws Exception
     */
    public function onStart(swoole_server $server)
    {
        $listeners = fnc()->c()->get('swoole.listeners', []);
        foreach ($listeners as $listener) {
            switch ($listener['sock_type']) {
                case SWOOLE_SOCK_UDP:
                    $sockType = 'udp';
                    break;
                case SWOOLE_SOCK_TCP:
                    $sockType = 'tcp';
                    break;
                default:
                    $sockType = 'sock_type:' . $listener['sock_type'];
            }

            $this->getIO()->title('<ft-red-bold>' . sprintf('Listen : %s://%s:%s', $sockType, $listener['host'], $listener['port']) . '</ft-red-bold>');
        }
    }

    /**
     * 当管理进程启动时触发此事件
     * @param swoole_server $server
     * @throws Exception
     */
    public function onManagerStart(swoole_server $server)
    {
        SwooleHelper::setProcessRename($this->getServerConfigName() . ' manager');
        $this->writelnBlock(sprintf('服务管理 PID [%s] 已经启动', $server->manager_pid));
    }

    /**
     * 事件在 Worker 进程 / Task 进程启动时发生，这里创建的对象可以在进程生命周期内使用
     * @param swoole_server $server
     * @param               $workerId
     */
    public function onWorkerStart(swoole_server $server, $workerId)
    {
        $worker_name = $server->taskworker ? 'task' : 'worker';
        $tag = '%s';
        switch ($worker_name) {
            case 'task':
                $tag = '<bf-yellow>%s</bf-yellow>';
                break;
            case 'worker':
                $tag = '<bf-blue>%s</bf-blue>';
                break;
            default:
        }
        SwooleHelper::setProcessRename($this->getServerConfigName() . ' ' . $worker_name);
        $this->getIO()->writeln(sprintf('服务 ' . $tag . ' <ft-blue-bold>[%s]</ft-blue-bold> 已经启动 [%s]', ucfirst($worker_name), $server->worker_pid, $workerId));
    }
}