<?php
// +----------------------------------------------------------------------
// | Created by linshan. 版权所有 @
// +----------------------------------------------------------------------
// | Copyright (c) 2020 All rights reserved.
// +----------------------------------------------------------------------
// | Technology changes the world . Accumulation makes people grow .
// +----------------------------------------------------------------------
// | Author: kaka梦很美 <1099013371@qq.com>
// +----------------------------------------------------------------------

namespace ShugaChara\Framework\Console;

use ShugaChara\Console\Command as ConsoleCommand;

/**
 * Class Command
 * @package ShugaChara\Framework\Console
 */
class Command extends ConsoleCommand
{
    /**
     * Script name
     * @var
     */
    protected static $name;

    /**
     * Script description
     * @var
     */
    protected static $description;

    /**
     * Console configure
     */
    protected function configure()
    {
        parent::configure(); // TODO: Change the autogenerated stub

        $this->setName(static::$name);
        $this->setDescription(static::$description);
    }
}

